apiVersion: batch/v1
kind: Job
metadata:
  name: wrk-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: wrk-container
          image: ghcr.io/himanshumps/pertaasr-wrk:latest
          args: ["-c20", "-d2m","http://rust-server.himanshumps-1-dev.svc.cluster.local:8080/"]
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              # It is best practice to set requests as well
              cpu: "2"
              memory: "4Gi"
      restartPolicy: OnFailure